version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - 8000:8000
    env_file: 
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 --log-level info --access-logfile "-" --error-logfile "-" "flaskr:create_app()"
