version: "3.2"
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_ROOT_URL
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_SMTP_ENABLED
      - GF_SMTP_HOST
      - GF_SMTP_USER
      - GF_SMTP_FROM_ADDRESS
      - GF_SMTP_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP
      - GF_ALERTING_ERROR_OR_TIMEOUT

volumes:
  grafana_data: {}
