version: '2'
services:
  web:
    container_name: gate
    image: nginx
    volumes:
     - ./config/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    network_mode: "host"
    ports:
     - 80:80
     - 443:443
